### ISSUE TITLE
Move the `reopen` from `RPC` to `SuspendResume`?

### ISSUE THREAD

**Issue by stoffeastrom** [qlik-oss/enigma.js#144]
Looking through the code base and [this](https://github.com/qlik-oss/enigma.js/blob/master/src/rpc.js#L54-L86) caught my eye. Imho this could definitely be in the `SuspendResume` class instead. It's tightly coupled to that logic and the `QIX` engine. There might be reasons that not are obvious but leaving this here for discussion ;).

Also since the emitted events in `Session`now seems to conform to `event:action` or similar the `suspended` events could be `suspended:manual`, `suspended:network` and support the `suspended:*` notation.

This is only my two cents so feel free to close this :)

**Comment by marcusoffesson** [comment]
I agree, `RPC::reopen()` is conceptually a part of the suspend/resume logic and it definitely fits better in the `SuspendResume` class. Let's look into the possibilities to move it!

I would say that the session events are conforms to `type:event` rather than `event:action`. IMHO, the event should still be `suspended` while the reason is event data.

**Comment by peol** [comment]
+1 on moving `reopen`! Will send a PR during the week.
