### ISSUE TITLE
How to identify which qix schema to use?

### ISSUE THREAD

**Issue by goldbergjeffrey** [qlik-oss/enigma.js#147]
### Description

Is there a way to identify which version of the qix schema to load up based on the version of Qlik Sense being talked to?

If so, how would one dynamically require the proper qix schema?

Are qix schemas backward compatible?

**Comment by marcusoffesson** [comment]
Hi!

The best way to explore API changes between QIX engine versions is to use the (newly released) [API Insights](https://api-insights.qlik.com/) site.

Regarding dynamic loading of QIX schema; we've discussed the possibility of fetching the schema from the server (via HTTP REST, not over the WebSocket). However, this would introduce a number of complications and we've not yet reached a conclusion if this is something we should implement or not.

**Comment by peol** [comment]
In addition to @marcusoffesson 's answer:
QIX schemas are backwards compatible in, i.e. if you use version 12.28.0 of the schema, you should be able to safely use any schema >= 12.28.0 as long as the _major_ version (12) is the same, as per the semantic versioning spec.

Generally, you wouldn't need to dynamically resolve the proper QIX schema, if there are new QIX methods in a version you use, you update the schema definition you need, otherwise you may use your current one as long as the QIX Engine version used isn't a new major version (which may have removed a QIX method you use, this can be seen in the API Insights page linked above).
