### ISSUE TITLE
ImportApp method does not exist anymore in EngineAPI help but is in schema 12.20.0

### ISSUE THREAD

**Issue by QHose** [qlik-oss/enigma.js#162]
hi,

Sense removed ImportApp from the dev help, but it is available in engima? (I suspect they recommend QRS, that was in the old 3.0 help)

**Comment by marcusoffesson** [comment]
Good question!
Enigma will generate a function for it since it exists in the schema. However, I'm not sure if it still exist and works on the engine side. I would not build a solution that expects it to work as it's no longer in the official documentation.

**Comment by peol** [comment]
This QIX method should not be used directly by end-users since there are additional steps needed in Qlik Sense Enterprise that the Repository has to do, which won't be executed if the end-user used the QIX method directly, hence the removal.

It is still used internally by Repository and therefore part of the schema definition still. As noted, if APIs aren't documented, you should not rely on them (even if the schema may contain it). We are looking into the schema definitions in parallel to enigma.js so this may change in the future.
