### ISSUE TITLE
unsecure config key is tricky since it is negative

### ISSUE THREAD

**Issue by seriousben** [qlik-oss/enigma.js#30]
I would expect it to be `secure` instead of `unsecure` to reduce errors.

**Comment by peol** [comment]
Hi.

The main reasons behind the unconventional naming of this configuration property was:

* Internal backwards compatibility
* The default for enigma.js is to run securely, and to reduce the number of properties we set (i.e. if it's falsy, we can omit setting the property)

Personally I don't think our reasons for the naming is good enough if it is confusing, and I'm all for deprecating `unsecure` for `secure`.

This issue is up for grabs.
