### ISSUE TITLE
Problem getting serialzedapp working

### ISSUE THREAD

**Issue by MartinNorman** [qlik-oss/enigma.js#343]
### Problem getting serialzedapp working

Hello, I'm trying to create a solution where I can compare 2 versions of the same app.
For instance between stage and prod. My plan is to use Alexanders serializeapp but I'm having problems getting it to work. I'm fairly new to using the backend APIs (javascript, promises and so on) so this is most likely my fault but I seem to be stuck at the moment so I thought why not ask the experts...

What I want to do is figure out which apps exist and for each app use serializeapp and get back the JSON string. This I want to store as files for further processing.
The end result is an app in Sense showing the status of all your apps between prod, stage and development. I.e. are there differences and if so what differences are there.

This is the code I'm using:
const enigma = require('enigma.js')
const WebSocket = require('ws')
const serializeapp = require('serializeapp')
const schema = require('enigma.js/schemas/12.20.0.json');
const session = enigma.create({
  schema,
  url: 'ws://localhost:9076/app/engineData',
  createSocket: url => new WebSocket(url)
});
	
function getdata(AppName) {
	session.open()
	.then((global) => global.openDoc(AppName)) 
	.then((app) => serializeapp(app))
	.then(result => fs.writeFile('result/' + AppName + '.json', JSON.stringify(result)))
	.then((close) => session.close())
	.then(() => console.log(AppName), function(err) {
		console.log(err);
	});
}

session.open()
	.then(function(global) {
	global.getDocList().then(function(docList) {
	session.close();
	for (i = 0; i < docList.length; i++) {
		var AppName = docList[i].qDocName;	
		getdata(AppName);
	}
	});
});

Running this results in the following error:
Error: Not connected
    at RPC.send (C:\mano\NodeJS\node_modules\enigma.js\enigma.js:1578:36)
    at C:\mano\NodeJS\node_modules\enigma.js\enigma.js:808:35
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

If I comment out the session.close() row I get an error saying
{ Error: App already open
    at Intercept.errorInterceptor (C:\mano\NodeJS\node_modules\enigma.js\enigma.js:2466:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 1002, parameter: 'IntUtb20160616.qvf' }

I'm pretty certain the problem has to do with the session. I'm guessing I'm not allowed to use the same session for different apps. I have got this to work by hardcoding a specific app as in your examples but I need my solution to be more dynamic.

I have tried the Qsock way first  and I seem to have the same problem.
When I saw that there is a session.close method when using the enigma solution I thought I had cracked it but apparently not.
Any pointers in the right direction would be greatly appreciated.

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. ...

##### Expected behavior
In my case I'm expecting 15 files in the resutls folder.
[What you expected to happen]

##### Actual behavior
Well, different error messages no matter what I have tried.
[What actually happened]

### Environment
Windows 10
##### Library
```
[X] Node.js
[ ] Browser
```
##### Operating system
```
[X] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense
```
[X] Desktop
[ ] Enterprise
```
### Versions

* Node.js: v8.9.1
* Browser: Chrome Version 63.0.3239.84 (Officiell version) (64 bitar)
* Qlik Sense: Desktop September 2017 (11.14.3)
* Operating system: Windows 10
* [Other relevant versions]

**Comment by peol** [comment]
Hey @MartinNorman, god fortsättning!

We're currently in vacation mode but I may be able to give you some pointers, otherwise you may have to wait until next week when some of us are officially back :)

Some pointers:

* When you are working with QIX Engine documents (or "apps" in the Sense world) you generally need to dedicate one session to each document, just as you suspected. You can run `enigma.create()` with a URL unique to each document, e.g. `ws://localhost:4848/app/the-app.qvf` and then doing `global.openDoc('the-app.qvf')` to get the `doc` reference in your `getdata()` function.
* Once you are finished with your document, do `session.close()` for that specific enigma session.
* I'm not familiar with `serializeapp` but I'll assume it returns a promise or you may need to do something else here to wait for the serialization to finish.
* `fs.writeFile` does not by default return a promise (in newer Node.js versions, you may use `require('util').promisify()` I believe).

Also, you may have some success on the [Qlik Branch slack](http://branch.qlik.com/slack) if you still are having problems, there may be people active there during this week.

Good luck!

**Comment by MartinNorman** [comment]
Thank you for your reply.
I will try this and see if I can get it to work.

**Comment by peol** [comment]
@MartinNorman Any updates or could we close this one?

**Comment by MartinNorman** [comment]
Hello, 
This issue can be closed.
You were right, the problem was that I was using the same session to open more than one app.

Thank you for your help.

br
Martin

**Comment by peol** [comment]
@MartinNorman Awesome, great that you got further into your project. Don't hesitate to file other issues if you find any!

**Comment by itsmeravitejak** [comment]
Great this has helped me a lot ,  the problem is that people get started with the examples like this one 
https://github.com/qlik-oss/enigma.js/blob/master/docs/api.md#enigmacreateconfig
where session is made a constant .  The pointers which you have provided above had helped us refactoring our code accordingly to open two different apps using enigma , I guess this info also needs to be in the enigma wiki somewhere so that new users can also get to know these things
