### ISSUE TITLE
app.GetAllInfos not working in node.js

### ISSUE THREAD

**Issue by cookiejest** [qlik-oss/enigma.js#355]
### Description

I am attempting to use app.GetAllInfos to retrieve all the generic objects inside node.js using Enigma but it is not recognised as a function. What am I doing wrong

Here is my code:

`
    const config = {
      hostname: 'localhost',
      port: '4848',
      createSocket: url => new WebSocket(url),
    };

    var session = enigma.create(enigmaInstance(config, docId));

    session.open()
      .then(function (global) {
        return global.openDoc(docId, '', '', '', false)

      })
      .then(function (app) {
        console.log("app Opened");
        console.log(app);
        return app.GetAllInfos()
      })
      .then(function (genericobjects) {
        console.log('THE generic objects', genericobjects);
        return;
      })
      .then(function () {
        session.close()
          .then(function () {
            console.log("session closed.")
          })
      })
      .catch(function (error) {
        console.log(error);
      })

  })`

##### Expected behavior

I am expecting it to return a list of generic objects

##### Actual behavior

I get the error message:

`TypeError: app.GetAllInfos is not a function`

##### Library
```
[X ] Node.js
[ ] Browser
```
##### Operating system
```
[ x] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense
```
[x ] Desktop
[ ] Enterprise
```
### Versions

* Node.js: 
* Browser: na
* Qlik Sense: 3.2
* Operating system:  windows
* [Other relevant versions]

**Comment by peol** [comment]
Hi @cookiejest!

enigma.js uses camel-casing for the QIX Engine API, noted here: https://github.com/qlik-oss/enigma.js/blob/master/docs/concepts.md#schemas-the-qix-interface so basically any QIX method you use should start with lowercase instead of uppercase character (`OpenDoc` -> `openDoc`, etc.). This is because in JavaScript, conventions state that uppercase functions are classes (which is not the case here).

Feel free to open up/file another issue if you still have trouble!
